export interface PresaleDetails {
    id: number,
    presaleId?: number | null,
    productId: number,
    quantityRequested: number,
    quantityDelivered: number | null,
    productBranchId: number,
    branchId: number,
    priceTypeName: string,
    priceTypeId: number,
    unitPrice: number,
    finalUnitPrice: number | null,
    subtotalRequested: number,
    subtotalDelivered: number | null,
    userId: number,
    state: boolean,
    createdAt?: string | null,
    updatedAt?: string | null,
    productName: string,
    productBarcode?: number | null,
    currentStock: number | null
}

export interface PresaleStatusHistory {
    id: number,
    presaleId: Number,
    previousStatus: string | null,
    newStatus?: string | null,
    notes: string | null,
    userId: number,
    createdAt?: string | null,
}

export interface Presale {
    id: number,
    clientId: number,
    businessId: number | null,
    branchId: number | null,
    presellerId?: number | null,
    branchName?: string | null,
    clientName?: string | null,
    clientLastName?: string | null,
    clientPhone?: number | null,
    presellerName?: string | null,
    distributorId: number | null,
    distributorName?: string | null,
    businessName?: string | null,
    createdAt?: string,
    updatedAt?: string,
    deliveryDate?: string,
    deliveredAt?: string | null,
    status: string,
    subtotal: number,
    total: number,
    notes?: string | null,
    deliveryNotes?: string | null,
    userId: number,
    state: boolean,
    details?: PresaleDetails[],
    presaleStatusHistory?: PresaleStatusHistory 
}